//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Route.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Products
    {
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Ürün Adý Boþ Olamaz")]
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        [Required(ErrorMessage = "Miktar Boþ Olamaz")]
        public string QuantityPerUnit { get; set; }
        [Required(ErrorMessage = "Fiyat Boþ Olamaz")]
        [Range(5, 500, ErrorMessage = "Fiyat Aralýðý yanlýþ 5-500 arasý deðer girin")]
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
